version: "3.8"
services:
  backend:
    build: .
    container_name: tyque-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
    working_dir: /app
