version: '3.8'
services:
  backend:
    build: .
    container_name: tyque-backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://<usuario>:<password>@<cluster>.mongodb.net/<dbname>?retryWrites=true&w=majority
